#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    project_rooter_outermost = false

    # coc/lsp support
    autocomplete_method = 'coc'

    # File Manager Plugin
    # Supports: nerdtree (defaul), vimfiler (vimproc.vim needed), defx (+py3 feature needed)
    filemanager = "vimfiler"

    # Enable/Disable SpaceVim layers


    # Autocomplete
    [[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

    # Shell
    [[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

    # Language completion support (Just sh/zsh/fish, etc for now.
    [[layers]]
    name = 'lang#sh'

   # coc/lsp support
    [[layers]] 
    name = 'lsp'
    filetypes = [
      'c',
      'cpp',
      'dart',
      'sh',
      'fish',
      'vim'
    ]
    [layers.override_cmd]
      c = ['ccls', '--log-file=/tmp/ccls.log']
      cpp = ['ccls', '--log-file=/tmp/ccls.log']

# Git support layers
    [[layers]]
    name = 'git'
    name = 'github'
    name = 'versioncontrol'

    # Fuzzy File Finder
    [[layers]]
    name = 'fzf'

    # Better integration with tmux
    [[layers]]
    name = 'tmux'

    # TreeSitter (instead of NerdTree)
    [[layers]]
    name = 'treesitter'

    # Disable NerdTree (trying TreeSitter insteadi).
    [[layers]]
    name = 'nerdtree'
    enabled = 'false'

[[custom_plugins]]
  repo = "dracula/vim"
  name = "dracula"
  merged = false

