commit_exclude_git_config = false
[repos."/home/paul/.local/share/chezmoi"]
include = []
exclude = []
max_depth = 255

[repos."/home/paul/Development/dura-status"]
include = []
exclude = []
max_depth = 255

[repos."/mnt/d/paulc/Development/Obsidian"]
include = []
exclude = []
max_depth = 255
