
[font]
size = 16.0

[font.bold]
family = "Pragmasevka Nerd Font"

[font.bold_italic]
family = "Pragmasevka Nerd Font"

[font.italic]
family = "Pragmasevka Nerd Font"

[font.normal]
family = "Pragmasevka Nerd Font"

[window.padding]
x = 10
y = 5

[general]
import = ["/Users/pjc/.config/alacritty/colors/nord.toml"]
